### ISSUE TITLE
Rendering Issue - CoordinatorLayout

### ISSUE THREAD

**Issue by VidyasagarMSC** [VidyasagarMSC/WatBot-Kotlin#1]
**Failed to load AppCompat ActionBar with unknown error**

java.lang.ClassNotFoundException: android.support.v4.view.TintableBackgroundView
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:182)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:56)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:120)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:215)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.android.tools.idea.rendering.RenderClassLoader.defineClassAndPackage(RenderClassLoader.java:177)
	at com.android.tools.idea.rendering.RenderClassLoader.loadClassFromJar(RenderClassLoader.java:92)
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:172)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:56)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:120)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:215)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:500)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:254)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:215)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadClass(LayoutlibCallbackImpl.java:213)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:336)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:155)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:723)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:225)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:866)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:840)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:90)
	at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:52)
	at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:46)
	at com.android.layoutlib.bridge.impl.Layout.createNavBar(Layout.java:284)
	at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:140)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:297)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:382)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:591)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:739)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sam-almighty** [comment]
Fixed Text rendering issue #2 Resolved.
